name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        echo "GO111MODULE=on" >> $GITHUB_ENV
        GOOS=windows GOARCH=amd64 go build -o bin/
        GOOS=linux   GOARCH=amd64 go build -o bin/
      
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./bin/
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./bin/
