name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Install dependencies
      run: |
        sudo apt-get install libgl1-mesa-dev xorg-dev -y
        go get github.com/go-gl/gl/v4.6-core/gl
        go get github.com/go-gl/glfw/v3.3/glfw
        

    - name: Build
      run: |
        echo "GO111MODULE=on" >> $GITHUB_ENV
        CGO_ENABLED=1
        GOOS=linux   GOARCH=amd64 go build -o bin/conways-gol
      
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./bin/


  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Install dependencies
      run: |
        go get github.com/go-gl/gl/v4.6-core/gl
        go get github.com/go-gl/glfw/v3.3/glfw
        

    - name: Build
      run: |
        echo "GO111MODULE=on" >> $GITHUB_ENV
        CGO_ENABLED=1
        GOOS=windows   GOARCH=amd64 go build -o bin/conways-gol.exe
      
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./bin/
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./bin/
